### ISSUE TITLE
Check for available disk space

### ISSUE THREAD

**Issue by schultyy** [travis-ci/travis-enterprise-worker-installers#8]
We need around 40GB of total disk space in order to pull down all build images. If less is present the installer should bail out for now.

**Comment by schultyy** [comment]
@bnferguson @acnagy @danishkhan @mariana-gu What's your opinion on this? Shall we just enforce the disk sizes or should this rather be a warning letting users know that they should have 40GB for the best experience? 

For the warning my though is that they might run on a small machine with just one or two build containers instead of all of them, which should be fine.

**Comment by bnferguson** [comment]
I'd say bail with an error but provide a switch to override (I mean, we don't pull down all images in our tests in worker). Though part of me doesn't want to provide a switch because if you know enough to only pull down the two workers you need (because you know how we route things) then you're gonna be just fine hacking our install script. 

But I would def bail by default, else we'll have people roll right through not reading things.
